---

language: elixir

elixir:
  - 1.0.5
  - 1.1.1
  - 1.2.6
  - 1.3.4
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.4
  - 1.8.1

otp_release:
  - 17.5
  - 18.3
  - 19.3
  - 20.1
  - 21.2

env:
  - MIX_ENV=prod
  - MIX_ENV=dev

matrix:
  exclude:
    - elixir: 1.0.5
      env: MIX_ENV=dev
    - elixir: 1.0.5
      otp_release: 19.3
    - elixir: 1.0.5
      otp_release: 20.1
    - elixir: 1.0.5
      otp_release: 21.2


before_install:
  - kerl update releases
  - kerl list releases

before_script:
  - mix deps.get
  - mix deps.compile

script:
  - mix compile
